version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo prepare Build on `date`
      - echo login ecr
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com 
      - COMMIT_ID=$(echo $REVISION_ID | cut -c 1-7)
      - echo "codebuildから実行する場合は,gitコマンドで取得する"
      - echo show COMMIT_ID ....
      - echo $COMMIT_ID
  pre_build:
    commands:
      - npm install
      - echo do test
      - npm test
      - echo docker build
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $IMAGE_REPO_NAME:$COMMIT_ID
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:$COMMIT_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID
  post_build:
    commands:
      - echo post build on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID
      - aws lambda update-function-code --function-name sample-cicd-function --image-uri  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID --region $AWS_DEFAULT_REGION